server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Trỏ mọi request về index.html để React Router xử lý
        try_files $uri $uri/ /index.html; 
    }
}